<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Use Meta
    |--------------------------------------------------------------------------
    |
    | If true, Markdown Plus expects a leading meta section in your markdown
    | file, separated by the following section splitter
    |
    */
    'use_meta' => true,
    /*
    |--------------------------------------------------------------------------
    | Section Splitter
    |--------------------------------------------------------------------------
    |
    | Splitter to divide the meta- and the content section
    | Default: /\s+-{3,}\s+/ --> one or more whitespace
    | characters, 3 or more dashes, one ore more
    | whitespace characters
    |
    */
   
    'section_splitter' => '/\s+-{3,}\s+/',

    /*
    |--------------------------------------------------------------------------
    | Use Markdown Extra
    |--------------------------------------------------------------------------
    |
    | Use Markdown with extra, for Example
    | https://michelf.ca/projects/php-markdown/extra/#fenced-code-blocks
    |
    */

    'use_extra'            => true,

    /*
    |--------------------------------------------------------------------------
    | Options for Michelf PHP Markdown
    |--------------------------------------------------------------------------
    |
    | Reference: https://michelf.ca/projects/php-markdown/configuration/
    |
    */

    'markdown_parser_options' => [

        /*
        |--------------------------------------------------------------------------
        | Suffix for empty HTML Elements
        |--------------------------------------------------------------------------
        |
        | This is the string used to close tags for HTML elements with no content
        | such as <br> and <hr>. The default value creates XML-style empty
        | element tags which are also valid in HTML 5
        */
       
        'empty_element_suffix' => ' />',

        /*
        |--------------------------------------------------------------------------
        | Tab Width
        |--------------------------------------------------------------------------
        |
        | Tab character with. This is the width of a tab character on input.
        | Changing this will affect how many spaces a tab character represents
        |
        */

        'tab_width'            => 4,

        /*
        |--------------------------------------------------------------------------
        | No markup
        |--------------------------------------------------------------------------
        |
        | Setting this variable to true will prevent HTML tags
        | in the input from being passed to the output
        |
        */

        'no_markup'            => false,

        /*
        |--------------------------------------------------------------------------
        | No entities
        |--------------------------------------------------------------------------
        |
        | Setting this variable to true will prevent HTML entities (such as &lt;)
        | from being passed verbatim in the output as it is the standard
        | with Markdown. Instead, the HTML output will be &amp;tl; and
        | once shown in shown the browser it will match
        | perfectly what was written.
        |
        */

        'no_entities'          => false,

        /*
        |--------------------------------------------------------------------------
        | Predefined URL
        |--------------------------------------------------------------------------
        |
        | You can predefine reference links by setting predef_urlsto a list of
        | urls where the key is the name of the reference.
        | array('ref' => '//goo.gl') --> [google][ref]
        |
        */

        'predef_urls'          => [],

        /*
        |--------------------------------------------------------------------------
        | Predefined titles
        |--------------------------------------------------------------------------
        |
        | Use predef_titles to set the title of the link references passed in
        | predef_urls. As for predef_urls, the key is the reference name
        |
        */

        'predef_titles'        => [],

        /*
        |--------------------------------------------------------------------------
        | Markdown Extra Options
        |--------------------------------------------------------------------------
        */

        /*
        |--------------------------------------------------------------------------
        | Footnotes ID prefix
        |--------------------------------------------------------------------------
        |
        | A prefix for the id attributes generated by footnotes. This is useful
        | if you have multiple Markdown documents displayed inside one
        | HTML document to avoid footnote ids to clash each other
        | Footnotes reference:
        | https://michelf.ca/projects/php-markdown/extra/#footnotes
        |
        */

        'fn_id_prefix'         => '',

        /*
        |--------------------------------------------------------------------------
        | Footnotes link/backlink title
        |--------------------------------------------------------------------------
        |
        | An optional title attribute for footnotes links and backlinks.
        | Browsers usually show this as a tooltip
        | when the mouse is over the link.
        |
        */
       
        'fn_link_title'        => '',

        'fn_backlink_title'    => '',

        /*
        |--------------------------------------------------------------------------
        | Footnotes link/backlink class
        |--------------------------------------------------------------------------
        |
        | The class attribute to use for footnotes links and backlinks
        |
        */

        'fn_link_class'        => 'footnote-ref',

        'fn_backlink_class'    => 'footnote-backref',

        /*
        |--------------------------------------------------------------------------
        | Code class prefix
        |--------------------------------------------------------------------------
        |
        | An optional prefix for the class names associated with fenced code blocks.
        | This will be prepended to the class name if you write your
        | fenced code block this way
        |   ~~~~ .html
        |   <br>
        |   ~~~~
        |
        */

        'code_class_prefix'    => '',

        /*
        |--------------------------------------------------------------------------
        | Code attributes on pre tag
        |--------------------------------------------------------------------------
        |
        | When set to false (the default), attributes for code blocks
        | will go on the <code> tag; setting this to true will put
        | attributes on the <pre> tag instead
        |
        */

        'code_attr_on_pre'     => false,

        /*
        |--------------------------------------------------------------------------
        | Predefined abbreviations
        |--------------------------------------------------------------------------
        |
        | You can predefine abbreviations by setting predef_abbr to a list of
        | abbreviations where the key is the text of the abbreviation
        | and the value is the expanded name
        | https://michelf.ca/projects/php-markdown/extra/#abbr
        |
        */

        'predef_abbr'          => [],
    ],
];